### ISSUE TITLE
[BUG] - soscleaner crashes with too many users

### ISSUE THREAD

**Issue by skhobbs18** [soscleaner/soscleaner#166]
**Describe the bug**
soscleaner is exiting with exceptions from what appears to be too many users.

02-19 13:51:55 soscleaner DEBUG: Obfuscating User - root > obfuscateduser1
02-19 13:51:55 soscleaner DEBUG: Cleaning /data/tmp/soscleaner/soscleaner-2203576965888006/sos_commands/last/lastlog
02-19 13:51:55 soscleaner DEBUG: Obfuscating Line -          **Never logged in**

02-19 13:51:55 soscleaner DEBUG: Processing Line -          **Never logged in**

02-19 13:51:55 soscleaner ERROR: nothing to repeat
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/soscleaner.py", line 412, in _sub_username
    line = re.sub(r'\b%s\b(?i)' % user, o_user, line)
  File "/usr/lib64/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
  File "/usr/lib64/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
error: nothing to repeat
02-19 13:51:55 soscleaner ERROR: ('SUB_USERNAME_ERROR: Unable to obfuscate usernames on line - %s', '         **Never logged in**\n')
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/soscleaner.py", line 900, in _clean_line
    new_line = self._sub_username(new_line)  # Username substitution
  File "/usr/lib/python2.6/site-packages/soscleaner.py", line 419, in _sub_username
    raise Exception('SUB_USERNAME_ERROR: Unable to obfuscate usernames on line - %s', line)
Exception: ('SUB_USERNAME_ERROR: Unable to obfuscate usernames on line - %s', '         **Never logged in**\n')
02-19 13:51:55 soscleaner ERROR: CLEAN_LINE_ERROR: Cannot Clean Line -          **Never logged in**
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/soscleaner.py", line 919, in _clean_file
    new_l = self._clean_line(l, f)
  File "/usr/lib/python2.6/site-packages/soscleaner.py", line 906, in _clean_line
    raise Exception("CLEAN_LINE_ERROR: Cannot Clean Line - %s" % line)
Exception: CLEAN_LINE_ERROR: Cannot Clean Line -          **Never logged in**

**Expected behavior**
The tool should run as expected regardless of the amount of data being obfuscated.

 - OS: RHEL 7.7
 - Version soscleaner-0.4.4-2.el7.noarch

**Additional context**
It seems there are over 16000 users in the sosreport.

02-19 13:08:38 soscleaner INFO: Adding new obfuscated user: XXXXXX > obfuscateduser16639
02-19 13:08:38 soscleaner INFO: Adding new obfuscated user: XXXXXX > obfuscateduser16640

The cleaner debug log is available, however it contains customer sensitive data.  If you need something specific, I can scrub it and provide.

**Comment by slashdd** [comment]
16000 users is quite big.

I don't know if this is a legit soscleaner bug, or a python bug itself.

```
File "/usr/lib64/python2.6/re.py", line 151, in sub
return _compile(pattern, 0).sub(repl, string, count)
File "/usr/lib64/python2.6/re.py", line 245, in _compile
raise error, v # invalid expression
error: nothing to repeat
```

I'll try to reproduce in Ubuntu to compare the result.

**Comment by slashdd** [comment]
16000 users also seems quite extreme and a very corner case.

**Comment by skhobbs18** [comment]
Any updates on this issue?  My customer has asked for an update.

Thanks

**Comment by slashdd** [comment]
Hi skhobbs18,

sos 4.0 will have soscleaner natively. Some part of the new code has been merged already. I would invite you to test `sos clean` as it will most likely be the way forward now.

**Comment by slashdd** [comment]
Reference: https://github.com/sosreport/sos/issues/1987
