### ISSUE TITLE
[BUG] unable to obfuscate file environment

### ISSUE THREAD

**Issue by arif-ali** [soscleaner/soscleaner#169]
**Describe the bug**
When running soscleaner from a newly compiled from the latest master branch of the repo, it fails to obfuscate a file, and then errors out

**To Reproduce**
1. clone the latest master branch
1. build and install using he following command

       python3 ./setup.py build
       python3 ./setup.py install

1. run `sosreport --all-logs --batch --ticket-number 1234`
1. copy the resulting sosreport to local directory
1. run soscleaner against the generated sosreport
1. You will see the error

**Expected behavior**
I would expect the soscleaner to go through, and obfuscate or ignore the file, and then move onto the next file

**Screenshots**
```
root@sosclean-test:~/soscleaner# /usr/local/bin/soscleaner ~/sosreport-sosclean-test-12234-2020-03-25-irpoklz.tar.xz 
03-25 16:22:35 soscleaner CONSOLE: Log File Created at /tmp/soscleaner-2962435146253372/soscleaner-2962435146253372.log
03-25 16:22:35 soscleaner CONSOLE: SOSCleaner version: 0.4.4
03-25 16:22:35 soscleaner CONSOLE: soscleaner is a tool to help obfuscate sensitive information from an existing sosreport.
03-25 16:22:35 soscleaner CONSOLE: Please review the content before passing it along to any third party.
03-25 16:22:35 soscleaner CONSOLE: Creating Loopback Network Entry
03-25 16:22:35 soscleaner CONSOLE: Beginning SOSReport Extraction
03-25 16:23:30 soscleaner CONSOLE: Created New Obfuscated Network - 129.0.0.0/24
03-25 16:23:30 soscleaner CONSOLE: Created New Obfuscated Network - 130.0.0.0/32
03-25 16:23:30 soscleaner CONSOLE: Adding new obfuscated domain - redhat.com > ofuscateddomain1.com
03-25 16:23:30 soscleaner CONSOLE: Adding new obfuscated domain - localhost.localdomain > ofuscateddomain2.com
03-25 16:23:30 soscleaner CONSOLE: Adding new obfuscated domain - localdomain > ofuscateddomain3.com
03-25 16:23:30 soscleaner CONSOLE: Adding new obfuscated domain - localhost > ofuscateddomain4.com
03-25 16:23:30 soscleaner CONSOLE: Unable to locate user file - /tmp/soscleaner-2962435146253372/soscleaner-2962435146253372/sos_commands/last/lastlog_-u_1000-60000
03-25 16:23:30 soscleaner CONSOLE: Continuing without processing users file
03-25 16:23:30 soscleaner CONSOLE: IP Obfuscation Network Created - 128.0.0.0/8
03-25 16:23:30 soscleaner CONSOLE: *** SOSCleaner Processing ***
03-25 16:23:30 soscleaner ERROR: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/soscleaner-0.4.4-py3.6.egg/soscleaner.py", line 1041, in _clean_file
    tmp_file.write(new_l)
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/soscleaner-0.4.4-py3.6.egg/soscleaner.py", line 1041, in _clean_file
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/soscleaner", line 4, in <module>
    __import__('pkg_resources').run_script('soscleaner==0.4.4', 'soscleaner')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/soscleaner-0.4.4-py3.6.egg/EGG-INFO/scripts/soscleaner", line 71, in <module>
  File "/usr/local/lib/python3.6/dist-packages/soscleaner-0.4.4-py3.6.egg/EGG-INFO/scripts/soscleaner", line 67, in main
  File "/usr/local/lib/python3.6/dist-packages/soscleaner-0.4.4-py3.6.egg/soscleaner.py", line 1640, in clean_report
  File "/usr/local/lib/python3.6/dist-packages/soscleaner-0.4.4-py3.6.egg/soscleaner.py", line 1048, in _clean_file
Exception: CLEAN_FILE_ERROR: Unable to obfuscate file - /tmp/soscleaner-2962435146253372/soscleaner-2962435146253372/environment
```

**Desktop (please complete the following information):**
 - OS: Ubuntu bionic 18.04 LTS

**Other Info:**

The contents of the file is shown below

```
TERM=screen-256color
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/sbin:/usr/local/bin:/snap/bin
```

**Comment by slashdd** [comment]
Seems like it is caused by the fact you setup this up with py3.
soscleaner haven't been fully ported to py3. If you redo your setup w/ py2 it should be okay.

- Eric

**Comment by arif-ali** [comment]
Thanks @slashdd, you are correct :)

I know why I skipped py2, as when I installed, the base system was missing `future` and `configparser`, and didn't get installed by default. I'll open up an issue and PR later, when I have been able to repro that particular issue
